<?php

namespace Database\Seeders;

use App\Modules\Products\Models\ProductAttribute;
use Illuminate\Database\Seeder;

class ProductAttributeSeeder extends Seeder
{
    public function run(): void
    {
        $rows = [
            [
                'key' => 'candle_color',
                'label' => ['fa' => 'رنگ شمع', 'en' => 'Candle Color'],
                'icon_svg' => '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3a9 9 0 1 0 0 18h1a2 2 0 0 0 2-2v-.8a1.2 1.2 0 0 1 1.2-1.2H18a3 3 0 0 0 0-6h-1.2A7.8 7.8 0 0 0 12 3Z"/><circle cx="8.2" cy="12" r="1"/><circle cx="10.8" cy="8.8" r="1"/><circle cx="14" cy="8.8" r="1"/><circle cx="15.8" cy="11.8" r="1"/></svg>',
                'value_type' => 'color',
                'values' => [
                    ['value' => ['fa' => 'سفید', 'en' => 'White'], 'meta' => ['hex' => '#ffffff']],
                    ['value' => ['fa' => 'شیری', 'en' => 'Ivory'], 'meta' => ['hex' => '#fff8dc']],
                    ['value' => ['fa' => 'کرم', 'en' => 'Cream'], 'meta' => ['hex' => '#f5deb3']],
                    ['value' => ['fa' => 'بژ', 'en' => 'Beige'], 'meta' => ['hex' => '#f5f5dc']],
                    ['value' => ['fa' => 'طلایی', 'en' => 'Gold'], 'meta' => ['hex' => '#d4af37']],
                    ['value' => ['fa' => 'نقره ای', 'en' => 'Silver'], 'meta' => ['hex' => '#c0c0c0']],
                    ['value' => ['fa' => 'زرد', 'en' => 'Yellow'], 'meta' => ['hex' => '#ffd60a']],
                    ['value' => ['fa' => 'کهربایی', 'en' => 'Amber'], 'meta' => ['hex' => '#ffbf00']],
                    ['value' => ['fa' => 'نارنجی', 'en' => 'Orange'], 'meta' => ['hex' => '#ff8c00']],
                    ['value' => ['fa' => 'هلویی', 'en' => 'Peach'], 'meta' => ['hex' => '#ffcba4']],
                    ['value' => ['fa' => 'صورتی', 'en' => 'Pink'], 'meta' => ['hex' => '#ff69b4']],
                    ['value' => ['fa' => 'رزگلد', 'en' => 'Rose Gold'], 'meta' => ['hex' => '#b76e79']],
                    ['value' => ['fa' => 'قرمز', 'en' => 'Red'], 'meta' => ['hex' => '#dc2626']],
                    ['value' => ['fa' => 'زرشکی', 'en' => 'Burgundy'], 'meta' => ['hex' => '#800020']],
                    ['value' => ['fa' => 'یاسی', 'en' => 'Lilac'], 'meta' => ['hex' => '#c8a2c8']],
                    ['value' => ['fa' => 'بنفش', 'en' => 'Purple'], 'meta' => ['hex' => '#7e22ce']],
                    ['value' => ['fa' => 'بنفش تیره', 'en' => 'Dark Purple'], 'meta' => ['hex' => '#4b0082']],
                    ['value' => ['fa' => 'آبی آسمانی', 'en' => 'Sky Blue'], 'meta' => ['hex' => '#87ceeb']],
                    ['value' => ['fa' => 'آبی', 'en' => 'Blue'], 'meta' => ['hex' => '#2563eb']],
                    ['value' => ['fa' => 'سرمه ای', 'en' => 'Navy'], 'meta' => ['hex' => '#1e3a8a']],
                    ['value' => ['fa' => 'فیروزه ای', 'en' => 'Turquoise'], 'meta' => ['hex' => '#40e0d0']],
                    ['value' => ['fa' => 'سبز نعنایی', 'en' => 'Mint Green'], 'meta' => ['hex' => '#98ff98']],
                    ['value' => ['fa' => 'سبز', 'en' => 'Green'], 'meta' => ['hex' => '#16a34a']],
                    ['value' => ['fa' => 'زیتونی', 'en' => 'Olive'], 'meta' => ['hex' => '#808000']],
                    ['value' => ['fa' => 'قهوه ای روشن', 'en' => 'Light Brown'], 'meta' => ['hex' => '#a67b5b']],
                    ['value' => ['fa' => 'قهوه ای', 'en' => 'Brown'], 'meta' => ['hex' => '#6f4e37']],
                    ['value' => ['fa' => 'موکا', 'en' => 'Mocha'], 'meta' => ['hex' => '#967969']],
                    ['value' => ['fa' => 'خاکستری', 'en' => 'Gray'], 'meta' => ['hex' => '#9ca3af']],
                    ['value' => ['fa' => 'دودی', 'en' => 'Smoke Gray'], 'meta' => ['hex' => '#4b5563']],
                    ['value' => ['fa' => 'مشکی', 'en' => 'Black'], 'meta' => ['hex' => '#111111']],
                ],
            ],
            [
                'key' => 'candle_scent',
                'label' => ['fa' => 'رایحه شمع', 'en' => 'Candle Scent'],
                'icon_svg' => '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3c1.7 2.3 3.5 4 3.5 6.4A3.5 3.5 0 1 1 8.5 9.4C8.5 7 10.3 5.3 12 3Z"/><path d="M8 15c0-1.7 1.3-3 3-3s3 1.3 3 3"/><path d="M5 18c1.4-1 3-1.5 5-1.5s3.6.5 5 1.5"/><path d="M6.5 21c1-.6 2.2-1 3.5-1s2.5.4 3.5 1"/></svg>',
                'value_type' => 'select',
                'values' => [
                    ['value' => ['fa' => 'وانیل', 'en' => 'Vanilla']],
                    ['value' => ['fa' => 'دارچین', 'en' => 'Cinnamon']],
                    ['value' => ['fa' => 'قهوه', 'en' => 'Coffee']],
                    ['value' => ['fa' => 'شکلات', 'en' => 'Chocolate']],
                    ['value' => ['fa' => 'کارامل', 'en' => 'Caramel']],
                    ['value' => ['fa' => 'عسل', 'en' => 'Honey']],
                    ['value' => ['fa' => 'یاس', 'en' => 'Jasmine']],
                    ['value' => ['fa' => 'رز', 'en' => 'Rose']],
                    ['value' => ['fa' => 'اسطوخودوس', 'en' => 'Lavender']],
                    ['value' => ['fa' => 'یاسمن', 'en' => 'Jasmine Sambac']],
                    ['value' => ['fa' => 'شکوفه پرتقال', 'en' => 'Orange Blossom']],
                    ['value' => ['fa' => 'بنفشه', 'en' => 'Violet']],
                    ['value' => ['fa' => 'ارکیده', 'en' => 'Orchid']],
                    ['value' => ['fa' => 'یاس سفید', 'en' => 'White Jasmine']],
                    ['value' => ['fa' => 'چوب صندل', 'en' => 'Sandalwood']],
                    ['value' => ['fa' => 'عود', 'en' => 'Oud']],
                    ['value' => ['fa' => 'سدر', 'en' => 'Cedar']],
                    ['value' => ['fa' => 'پچولی', 'en' => 'Patchouli']],
                    ['value' => ['fa' => 'مشک', 'en' => 'Musk']],
                    ['value' => ['fa' => 'عنبر', 'en' => 'Ambergris']],
                    ['value' => ['fa' => 'لیموناد', 'en' => 'Lemonade']],
                    ['value' => ['fa' => 'لیمو', 'en' => 'Lemon']],
                    ['value' => ['fa' => 'پرتقال', 'en' => 'Orange']],
                    ['value' => ['fa' => 'گریپ فروت', 'en' => 'Grapefruit']],
                    ['value' => ['fa' => 'ترنج', 'en' => 'Bergamot']],
                    ['value' => ['fa' => 'سیب', 'en' => 'Apple']],
                    ['value' => ['fa' => 'انار', 'en' => 'Pomegranate']],
                    ['value' => ['fa' => 'توت فرنگی', 'en' => 'Strawberry']],
                    ['value' => ['fa' => 'انبه', 'en' => 'Mango']],
                    ['value' => ['fa' => 'نارگیل', 'en' => 'Coconut']],
                    ['value' => ['fa' => 'دریایی', 'en' => 'Ocean Breeze']],
                    ['value' => ['fa' => 'باران', 'en' => 'Rain']],
                    ['value' => ['fa' => 'پنبه', 'en' => 'Cotton']],
                    ['value' => ['fa' => 'پودر بچه', 'en' => 'Baby Powder']],
                    ['value' => ['fa' => 'نعناع', 'en' => 'Mint']],
                    ['value' => ['fa' => 'اکالیپتوس', 'en' => 'Eucalyptus']],
                    ['value' => ['fa' => 'بابونه', 'en' => 'Chamomile']],
                    ['value' => ['fa' => 'رزماری', 'en' => 'Rosemary']],
                    ['value' => ['fa' => 'سیترونلا', 'en' => 'Citronella']],
                    ['value' => ['fa' => 'بدون رایحه', 'en' => 'Unscented']],
                ],
            ],
            [
                'key' => 'candle_shape',
                'label' => ['fa' => 'شکل ظاهری شمع', 'en' => 'Candle Shape'],
                'icon_svg' => '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="4" y="9" width="4" height="8" rx="1"/><circle cx="12" cy="13" r="3"/><path d="M17 17h4l-2-8-2 8Z"/></svg>',
                'value_type' => 'select',
                'values' => [
                    ['value' => ['fa' => 'ستونی', 'en' => 'Pillar']],
                    ['value' => ['fa' => 'استوانه ای', 'en' => 'Cylinder']],
                    ['value' => ['fa' => 'مکعبی', 'en' => 'Cube']],
                    ['value' => ['fa' => 'قلمی', 'en' => 'Taper']],
                    ['value' => ['fa' => 'مخروطی', 'en' => 'Cone']],
                    ['value' => ['fa' => 'توپی', 'en' => 'Sphere']],
                    ['value' => ['fa' => 'تخم مرغی', 'en' => 'Egg']],
                    ['value' => ['fa' => 'موجی', 'en' => 'Wavy']],
                    ['value' => ['fa' => 'حلزونی', 'en' => 'Spiral']],
                    ['value' => ['fa' => 'هرمی', 'en' => 'Pyramid']],
                    ['value' => ['fa' => 'قلبی', 'en' => 'Heart']],
                    ['value' => ['fa' => 'گل', 'en' => 'Flower']],
                    ['value' => ['fa' => 'برگ', 'en' => 'Leaf']],
                    ['value' => ['fa' => 'ستاره ای', 'en' => 'Star']],
                    ['value' => ['fa' => 'ماه', 'en' => 'Moon']],
                    ['value' => ['fa' => 'حیوانات', 'en' => 'Animal']],
                    ['value' => ['fa' => 'فرشته', 'en' => 'Angel']],
                    ['value' => ['fa' => 'مجسمه ای', 'en' => 'Sculptural']],
                    ['value' => ['fa' => 'شناور', 'en' => 'Floating']],
                    ['value' => ['fa' => 'وارمر', 'en' => 'Tealight']],
                    ['value' => ['fa' => 'لیوانی', 'en' => 'Glass Jar']],
                    ['value' => ['fa' => 'کوزه ای', 'en' => 'Vase']],
                    ['value' => ['fa' => 'کاسه ای', 'en' => 'Bowl']],
                    ['value' => ['fa' => 'صدفی', 'en' => 'Shell']],
                    ['value' => ['fa' => 'کاپ کیکی', 'en' => 'Cupcake']],
                    ['value' => ['fa' => 'عدد و حروف', 'en' => 'Number and Letter']],
                ],
            ],
            [
                'key' => 'candle_wick',
                'label' => ['fa' => 'فیتیله شمع', 'en' => 'Candle Wick'],
                'icon_svg' => '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3c1.7 2.2 3 3.6 3 5.4A3 3 0 1 1 9 8.4C9 6.6 10.3 5.2 12 3Z"/><path d="M12 10v11"/><path d="M9 21h6"/></svg>',
                'value_type' => 'select',
                'values' => [
                    ['value' => ['fa' => 'فیتیله پنبه ای', 'en' => 'Cotton Wick']],
                    ['value' => ['fa' => 'فیتیله پنبه ای تخت', 'en' => 'Flat Cotton Wick']],
                    ['value' => ['fa' => 'فیتیله پنبه ای با هسته کاغذی', 'en' => 'Cotton Wick with Paper Core']],
                    ['value' => ['fa' => 'فیتیله چوبی', 'en' => 'Wood Wick']],
                    ['value' => ['fa' => 'فیتیله چوبی کراکل', 'en' => 'Crackling Wood Wick']],
                    ['value' => ['fa' => 'فیتیله کنفی', 'en' => 'Hemp Wick']],
                    ['value' => ['fa' => 'فیتیله بامبو', 'en' => 'Bamboo Wick']],
                    ['value' => ['fa' => 'فیتیله زینک دار', 'en' => 'Zinc-Core Wick']],
                    ['value' => ['fa' => 'فیتیله چندگانه', 'en' => 'Multi Wick']],
                    ['value' => ['fa' => 'فیتیله بدون سرب', 'en' => 'Lead-Free Wick']],
                ],
            ],
            [
                'key' => 'candle_type',
                'label' => ['fa' => 'نوع شمع', 'en' => 'Candle Type'],
                'icon_svg' => '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M8 20h8"/><path d="M9 20V9h6v11"/><path d="M12 3c1.6 2.1 3 3.6 3 5.1A3 3 0 0 1 9 8.1C9 6.6 10.4 5.1 12 3Z"/><path d="M7 12h10"/><path d="M10 15h4"/></svg>',
                'value_type' => 'select',
                'values' => [
                    ['value' => ['fa' => 'شمع عطری', 'en' => 'Scented Candle']],
                    ['value' => ['fa' => 'شمع دکوراتیو', 'en' => 'Decorative Candle']],
                    ['value' => ['fa' => 'شمع وارمر', 'en' => 'Tealight Candle']],
                    ['value' => ['fa' => 'شمع ستونی', 'en' => 'Pillar Candle']],
                    ['value' => ['fa' => 'شمع قلمی', 'en' => 'Taper Candle']],
                    ['value' => ['fa' => 'شمع شناور', 'en' => 'Floating Candle']],
                    ['value' => ['fa' => 'شمع لیوانی', 'en' => 'Jar Candle']],
                    ['value' => ['fa' => 'شمع ظرفی', 'en' => 'Container Candle']],
                    ['value' => ['fa' => 'شمع سویا', 'en' => 'Soy Candle']],
                    ['value' => ['fa' => 'شمع پارافینی', 'en' => 'Paraffin Candle']],
                    ['value' => ['fa' => 'شمع ژله ای', 'en' => 'Gel Candle']],
                    ['value' => ['fa' => 'شمع مومی عسل', 'en' => 'Beeswax Candle']],
                    ['value' => ['fa' => 'شمع تولد', 'en' => 'Birthday Candle']],
                    ['value' => ['fa' => 'شمع عددی', 'en' => 'Number Candle']],
                    ['value' => ['fa' => 'شمع مناسبتی', 'en' => 'Occasion Candle']],
                    ['value' => ['fa' => 'شمع ماساژ', 'en' => 'Massage Candle']],
                ],
            ],
            [
                'key' => 'candle_weight',
                'label' => ['fa' => 'وزن شمع', 'en' => 'Candle Weight'],
                'icon_svg' => '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3c1.2 1.8 2.5 3 2.5 4.5a2.5 2.5 0 1 1-5 0C9.5 6 10.8 4.8 12 3Z"/><path d="M7 7h10"/><path d="M8 7l-2 6a3 3 0 0 0 6 0L10 7"/><path d="M16 7l-2 6a3 3 0 0 0 6 0L18 7"/><path d="M12 13v7"/><path d="M9 20h6"/></svg>',
                'value_type' => 'select',
                'values' => [
                    ['value' => ['fa' => '50 گرم', 'en' => '50 g']],
                    ['value' => ['fa' => '80 گرم', 'en' => '80 g']],
                    ['value' => ['fa' => '100 گرم', 'en' => '100 g']],
                    ['value' => ['fa' => '150 گرم', 'en' => '150 g']],
                    ['value' => ['fa' => '200 گرم', 'en' => '200 g']],
                    ['value' => ['fa' => '250 گرم', 'en' => '250 g']],
                    ['value' => ['fa' => '300 گرم', 'en' => '300 g']],
                    ['value' => ['fa' => '400 گرم', 'en' => '400 g']],
                    ['value' => ['fa' => '500 گرم', 'en' => '500 g']],
                    ['value' => ['fa' => '750 گرم', 'en' => '750 g']],
                    ['value' => ['fa' => '1 کیلوگرم', 'en' => '1 kg']],
                ],
            ],
            [
                'key' => 'candle_dimensions',
                'label' => ['fa' => 'ابعاد شمع', 'en' => 'Candle Dimensions'],
                'icon_svg' => '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 6h14v12H5z"/><path d="M8 6v3"/><path d="M11 6v4"/><path d="M14 6v3"/><path d="M17 6v4"/><path d="M5 10h3"/><path d="M5 13h4"/><path d="M5 16h3"/><path d="M19 9v6"/><path d="M17.5 10.5 19 9l1.5 1.5"/><path d="M17.5 13.5 19 15l1.5-1.5"/></svg>',
                'value_type' => 'select',
                'values' => [
                    ['value' => ['fa' => '5x5 سانتی متر', 'en' => '5x5 cm']],
                    ['value' => ['fa' => '5x10 سانتی متر', 'en' => '5x10 cm']],
                    ['value' => ['fa' => '6x12 سانتی متر', 'en' => '6x12 cm']],
                    ['value' => ['fa' => '7x7 سانتی متر', 'en' => '7x7 cm']],
                    ['value' => ['fa' => '7x15 سانتی متر', 'en' => '7x15 cm']],
                    ['value' => ['fa' => '8x8 سانتی متر', 'en' => '8x8 cm']],
                    ['value' => ['fa' => '8x10 سانتی متر', 'en' => '8x10 cm']],
                    ['value' => ['fa' => '10x10 سانتی متر', 'en' => '10x10 cm']],
                    ['value' => ['fa' => '10x15 سانتی متر', 'en' => '10x15 cm']],
                ],
            ],
            [
                'key' => 'candle_burn_time',
                'label' => ['fa' => 'زمان اتمام شمع', 'en' => 'Burn Time'],
                'icon_svg' => '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="8"/><path d="M12 8v4l2.5 1.5"/><path d="M12 4c1.7 2.2 3 3.8 3 5.4A3 3 0 1 1 9 9.4C9 7.8 10.3 6.2 12 4Z"/></svg>',
                'value_type' => 'select',
                'values' => [
                    ['value' => ['fa' => '4 ساعت', 'en' => '4 h']],
                    ['value' => ['fa' => '6 ساعت', 'en' => '6 h']],
                    ['value' => ['fa' => '8 ساعت', 'en' => '8 h']],
                    ['value' => ['fa' => '12 ساعت', 'en' => '12 h']],
                    ['value' => ['fa' => '16 ساعت', 'en' => '16 h']],
                    ['value' => ['fa' => '24 ساعت', 'en' => '24 h']],
                    ['value' => ['fa' => '30 ساعت', 'en' => '30 h']],
                    ['value' => ['fa' => '40 ساعت', 'en' => '40 h']],
                    ['value' => ['fa' => '50 ساعت', 'en' => '50 h']],
                    ['value' => ['fa' => '60 ساعت', 'en' => '60 h']],
                    ['value' => ['fa' => '80 ساعت', 'en' => '80 h']],
                ],
            ],
        ];

        foreach ($rows as $index => $row) {
            $attribute = ProductAttribute::query()->updateOrCreate(
                ['key' => $row['key']],
                [
                    'label' => $row['label'],
                    'icon_svg' => $row['icon_svg'] ?? null,
                    'value_type' => $row['value_type'],
                    'sort_order' => $index,
                ]
            );

            foreach ($row['values'] as $valueIndex => $item) {
                $serialized = json_encode($item['value'], JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);

                $existing = $attribute->values()->where('value', $serialized)->first();

                if ($existing !== null) {
                    $existing->fill(['meta' => $item['meta'] ?? null, 'sort_order' => $valueIndex])->save();
                } else {
                    $attribute->values()->create([
                        'value' => $serialized,
                        'meta' => $item['meta'] ?? null,
                        'sort_order' => $valueIndex,
                    ]);
                }
            }
        }
    }
}